version: '3'
services:
  server:
    build:
      context: .
      dockerfile: /EasyTrip/Dockerfile
    ports: 
      - "12345-12349:12345-12349"
    volumes:
      - /EasyTrip/app/node_modules
      - .:/EasyTrip/app
    networks:
      - net1
  gui:
    build:
      context: .
      dockerfile: /EasyTripGUI/Dockerfile
    ports: 
      - "4200:4200"
    volumes:
      - /EasyTripGUI/app/node_modules
      - .:/EasyTripGUI/app
    networks:
      - net1
networks:
  net1: