openapi: 3.0.0
info:
  title: EasyTrip
  version: 1.0.0
  description: EasyTrip official API
  license:
    name: Licensed Under MIT
    url: https://spdx.org/licenses/MIT.html
  contact:
    name: JSONPlaceholder
    url: https://jsonplaceholder.typicode.com
servers:
  - url: http://localhost:12349
    description: EasyTrip server
  - url: http://localhost:12348
    description: Path Search server
  - url: http://localhost:12347
    description: Point Search server
  - url: http://localhost:12346
    description: OSM Tools server
  - url: http://localhost:12345
    description: Auth server
  
paths:
  '/v1/users/login':
    post:
      summary: Authentication of an user and get a new token
      description: Authentication of an used based on the username and password and get a token
      tags:
        - Auth Tools
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: 'user1'
                  required: true
                password:
                  type: string
                  example: 'user1_password'
                  required: true
      responses:
        '200':
          description: Token sucessfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
                description: User results object
        '400':
          $ref: '#/components/responses/BadRequest'

  '/v1/users/signup':
    post:
      summary: Create new user and get a new token
      description: Create a new user and get a token
      tags:
        - Auth Tools
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: 'user1'
                  required: true
                email:
                  type: string
                  example: 'user@domain.com'
                  required: true
                password:
                  type: string
                  example: 'user1_password'
                  required: true
                passwordConfirm:
                  type: string
                  example: 'user1_password'
                  required: true
      responses:
        '200':
          description: New user sucessfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
                description: User results object
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/ExistingUser'


  '/v1/routing/geocode':
    get:
      summary: Get coordinates and various informations of a given address
      description: Get coordinates and various informations of a given address
      tags:
        - OSM Tools
      parameters:
        - $ref: '#/components/parameters/address'
          description: Address to do geocode
        - $ref: '#/components/parameters/limit'
          description: Max number of geocode results
      responses:
        '200':
          description: Geocode results retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/geocode'
                description: Geocode results object
        '400':
          $ref: '#/components/responses/BadRequest'
        
  '/v1/weather/current':
    get:
      summary: Get current weather given a certain place
      tags:
        - Point Search
      parameters:
        - name: city
          in: query
          required: true
          schema:
            type: string
          description: City on which to get current weather status
      description: Get current weather status given a certain place
      responses:
        '200':
          description: Return a JSON with current weather status on given city
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Success of request
                  text:
                    type: string
                    description: description of the current weather status in natural language
                  message:
                    type: string
                    description: current weather statusDocumenti
  '/v1/weather/forecast':
    get:
      summary: Get weather forecast given a certain place
      tags:
        - Point Search
      parameters:
        - $ref: '#/components/parameters/city'
      description: Get weather forecasts up to 16 days given a certain place
      responses:
        '200':
          description: Success 
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Success of request
                  text:
                    type: string
                    description: description of the weather forecasts for the next 16 days in natuaral language
                  message:
                    type: array
                    description: array of weather forecasts of the next 16 days
  '/v1/bikes/networks':
    get:
      summary: Get data about bike sharing available in a certain place
      tags:
        - Point Search
      parameters:
        - $ref: '#/components/parameters/city'
      description: Get data about bike sharing available in a certain place
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Success of request
                  message:
                    type: object
                    properties:
                      company:
                        type: string
                        description: The company providing the bike sharing service
                      gbfs_href:
                        type: string
                        description: Website url of the bike sharing service
                      href:
                        type: string
                        description: resource URI on bike sharing API Website
                      id:
                        type: string
                        description: bike sharing identifier
                      location:
                        type: object
                        properties:
                          city:
                            type: string
                            description: City where the bike sharing service is available
                          country:
                            type: string
                            description: Country where the city is located
                          latitude:
                            type: number
                            description: latitute coordinate value
                          longitude:
                            type: number
                            description: longitude coordinate value
                      name:
                        type: string
                        description: name of the bike sharing service              
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Success of the Request 
                  message:
                    type: stringke
                    description: Empty message               

components:
  parameters:
    city:
      name: city
      in: query
      schema:
        type: string
      required: true
    address:
      name: address
      in: query
      schema:
        type: string
      required: true
    limit:
      name: limit
      in: query
      schema:
        type: integer
  schemas:
    user:   
      type: object
      properties:
        username:
          type: string
          description: username of the user
        token: 
          type: string
          description: token of the user    
    geocode:
      type: object
      properties:
        hits:
          type: array
          items:
            type: object
            description: Geocode result
            properties:
              point:
                type: object
                description: Coordinates
                properties:
                  lat:
                    type: number
                    description: Latitude
                  lng:
                    type: number
                    description: Longitude
              osm_id:
                type: string
                description: The OSM ID of the entity
              osm_type:
                type: string
                description: N = node, R = relation, W = way
              osm_key:
                type: string
                description: The OSM key of the entity
              name:
                type: string
                description: The name of the entity. Can be a boundary, POI, address, etc
              country:
                type: string
                description: The country of the address
              city:
                type: string
                description: The city of the address
              state:
                type: string
                description: The state of the address
              street:
                type: string
                description: The street of the address
              housenumber:
                type: string
                description: The housenumber of the address
              postcode:
                type: string
                description: The postcode of the address
  responses:
    BadRequest:
      description: Bad request
    ExistingUser:
      description: User already existing
    ServerError:
      description: Server error