openapi: 3.0.0
info:
  title: EasyTrip
  version: 1.0.0
  description: EasyTrip official API
  license:
    name: Licensed Under MIT
    url: https://spdx.org/licenses/MIT.html
  contact:
    name: JSONPlaceholder
    url: https://jsonplaceholder.typicode.com
servers:
  - url: http://localhost:12345
    description: Development server
paths:
  '/api/v1/weather/current':
    get:
      summary: Get current weather given a certain place
#      tags:
#        - Point search
      parameters:
        - name: city
          in: query
          required: true
          schema:
            type: string
          description: City on which to get current weather status
      description: Get current weather status given a certain place
      responses:
        '200':
          description: Return a JSON with current weather status on given city
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Success of request
                  text:
                    type: string
                    description: description of the current weather status in natural language
                  message:
                    type: string
                    description: current weather statusDocumenti
  '/api/v1/weather/forecast':
    get:
      summary: Get weather forecast given a certain place
#      tags:
#        - Point search
      parameters:
        - $ref: '#/components/parameters/city'
      description: Get weather forecasts up to 16 days given a certain place
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  text:
                    type: string
                  message:
                    type: array

components:
  parameters:
    city:
      name: city
      in: query
      schema:
        type: string
      required: true